/**
 * Author:fanlilin
 * Date:2024/3/18
 * Descrobe:
 */

import common from '@ohos.app.ability.common';
import util from '@ohos.util';
import { RKTProgress, RKTProgressStyle } from '../components/RKTProgress'
import RKTEventBus, { RKTEventData } from '../utils/RKTEventBus'

export class RKTUtil {

  public static context(x: any) {
    // let context = getContext(x).createModuleContext('rocketUI') as common.UIAbilityContext
  }

}

export default RKTUtil